http:
  port: 8888
server:
  port: 9999
  #http2:
  #  enabled: true
  # ssl:
  #    key-alias: bigoo-shop
  #   key-store: classpath:bigoo.keystore
  #  key-store-password: bigoo-shop
  #  key-store-type: PKCS12
spring:
  profiles:
    active: ${profile:dev}
  application:
    name: Bigoo-Admin

mybatis:
  type-aliases-package: com.jokey.bigoo.admin.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: false
  row-bounds-with-count: true

logging:
  level:
    com:
     jokey:
       bigoo:
         admin:
           mapper: debug