spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.102.147:3306/test_01?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456